#!/bin/bash

BUILD_TARGET=${1:-android_arm64_v8a}
WORKSPACE=${WORKSPACE:-$PWD}
WORKSPACE=`realpath $WORKSPACE`
EXECUTABLE=${EXECUTABLE:-$WORKSPACE/build_package_android}

if [[ "$BUILD_TARGET" != "android_arm64_v8a" && "$BUILD_TARGET" != "android_armv7" ]]; then
    echo "Usage: build_package [BUILD_TARGET]"
    echo "      BUILD_TARGET *MUST* be one of: android_arm64_v8a, android_armv7"
    exit -1
fi

# The container we use is: a12e/docker-qt:5.12-android_arm64_v8a
CONTAINER=${CONTAINER:-a12e/docker-qt:5.12-$BUILD_TARGET}
TIMESTAMP=`date +%Y%m%d`
BUILD_ID=${BUILD_ID:-$TIMESTAMP}

CACHE_DIR=$WORKSPACE/.cache
CCACHE_DIR=$CACHE_DIR/.ccache
GRADLE_DIR=$CACHE_DIR/.gradle
MAVEN_DIR=$CACHE_DIR/.m2

mkdir -p $WORKSPACE
mkdir -p $CCACHE_DIR
mkdir -p $GRADLE_DIR

[[ -v DISPLAY ]] && xhost +local:root

docker run --rm \
           -e BUILD_ID="$BUILD_ID" \
           -e WORKSPACE="$WORKSPACE" \
           -e CCACHE_DIR="$CCACHE_DIR" \
           -e GRADLE_USER_HOME="$GRADLE_DIR" \
           -e M2_HOME="$MAVEN_DIR" \
           -e MAVEN_HOME="$MAVEN_DIR" \
           -e BUILD_TARGET="$BUILD_TARGET" \
           -e ANDROID_KEYSTORE_FILE_CONTENTS="$ANDROID_KEYSTORE_FILE_CONTENTS" \
           -e ANDROID_KEYSTORE_ALIAS="$ANDROID_KEYSTORE_ALIAS" \
           -e ANDROID_KEYSTORE_PASS="$ANDROID_KEYSTORE_PASS" \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v $CCACHE_DIR:$CCACHE_DIR \
           -v $GRADLE_DIR:$GRADLE_DIR \
           -v $WORKSPACE:$WORKSPACE -it \
           -u $USER \
           $CONTAINER $EXECUTABLE
