#!/bin/bash

WORKSPACE=${WORKSPACE:-$PWD}
BUILD_DIR=$WORKSPACE/build
ANDROID_BUILD_DIR=$BUILD_DIR/android-build
OUTPUT_DIR=$WORKSPACE/output
#Got the platform from readme of https://github.com/a12e/docker-qt
SDK_PLATFORM=android-21


cd $WORKSPACE
#git submodule init
#git submodule update

rm -rf $ANDROID_BUILD_DIR
rm -rf $BUILD_DIR

mkdir -p $BUILD_DIR
mkdir -p $ANDROID_BUILD_DIR

cd $BUILD_DIR

# Run qmake, optional: ship the OpenSSL libraries
qmake -r .. ANDROID_EXTRA_LIBS+=$ANDROID_DEV/lib/libcrypto.so ANDROID_EXTRA_LIBS+=$ANDROID_DEV/lib/libssl.so
make -j`nproc`
make install INSTALL_ROOT=$ANDROID_BUILD_DIR

# Create APK
androiddeployqt --input android-libvolla-launcher.so-deployment-settings.json --output $ANDROID_BUILD_DIR --android-platform $SDK_PLATFORM --deployment bundled --gradle --release
